# Generated by Django 4.0 on 2023-05-04 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreRaza', models.CharField(max_length=20, verbose_name='Nombre d ela Raza')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoChip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Chip de la Mascota')),
                ('nombreMascota', models.CharField(max_length=30, verbose_name='Nombre de la Mascota')),
                ('edadMascota', models.IntegerField(verbose_name='Edad de la mascota')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raza')),
            ],
        ),
    ]
